export const SET_AMD_REQUIRE = 'SET_AMD_REQUIRE'

export const OPEN_BLOG = 'OPEN_BLOG'
export const ADD_POST = 'ADD_POST'
export const SET_BLOG_BASE_PATH = 'SET_BLOG_BASE_PATH'
export const CHANGE_POST = 'CHANGE_POST'
export const UNLOAD_ACTIVE_BLOG = 'UNLOAD_ACTIVE_BLOG'
